### ISSUE TITLE
Break out utility functions to the SDK.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-sdk#281]
Converting map[string]string to map[string]interface{}

Have some more. Need to add.

**Comment by MatthewHink** [comment]
There are quite a few of them from synse-snmp-plugin, snmp/core/util.go has some.

**Comment by edaniszewski** [comment]
converting `map[string]string` to `map[string]interface{}` shouldn't be needed, as there are no more `map[string]string` in sdk v1.0 (which should be ready to go soon)

as for other utils, if they are specific to the SDK and perform operations that are common for plugins, then it makes sense to fold them in, otherwise, it seems like it should be a plugin-level util, not an sdk-level util.

**Comment by edaniszewski** [comment]
closing as wontfix - the SDK does provide some synse/plugin specific utilities, but I don't believe it should provide generalized utility functions.
